[package]
name = "bevy_entropy"
version = "0.8.0-dev"
edition = "2018"
authors = [
    "Bevy Contributors <bevyengine@gmail.com>",
    "Christian Legnitto <christian@legnitto.com>",
]
description = "Provides entropy functionality for Bevy Engine"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "random", "entropy"]

[dependencies]
# bevy 
bevy_app = { path = "../bevy_app", version = "0.8.0-dev" }
bevy_utils = { path = "../bevy_utils", version = "0.8.0-dev" }
# other
rand = { version = "0.8", features = ["std_rng"] }

[dev-dependencies]
bevy_internal = { path = "../bevy_internal", version = "0.8.0-dev" }
bevy_ecs = { path = "../bevy_ecs", version = "0.8.0-dev" }
rand = { version = "0.8", features = ["std_rng", "small_rng"] }
